// <auto-generated />
using BeMarcas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeMarcas.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20220126172505_V.0.0.1")]
    partial class V001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeMarcas.Models.Marca", b =>
                {
                    b.Property<int>("Id_Marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cmarca")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Den_marca")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("FECHA_CARGA")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RegistroMca")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Viña")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id_Marca");

                    b.ToTable("Marca");
                });
#pragma warning restore 612, 618
        }
    }
}
